---
- name: Network Switch Config Saver
  hosts: allswitches
  # collect facts about controller
  # so that ansible_date_time is defined
  gather_facts: no

  # location on the controller
  vars_files:
    - ~/switch.creds

  tasks:        
  # v2.9 forward, this is required if you reference any ansible_date_time in your network playbooks
  - name: run local gather_facts on controller
    #setup:
    command: 'date +%Y-%m-%d'
    register: result
    vars:
        ansible_connection: local

  - name: Arista EOS fact collection
    eos_facts:
      gather_subset: all  # IMPORTANT! Look at the Return values at the bottom of the eos_facts
    when: ansible_network_os == "eos"

  - name: Cisco IOS fact collection
    ios_facts:
      gather_subset: all  
    when: ansible_network_os == "ios"

  - name: Cisco NXOS fact collection
    nxos_facts:
      gather_subset: all  
    when: ansible_network_os == "nxos"

  - name: Juniper JunOS fact collection
    junos_facts:
      gather_subset: all
    when: ansible_network_os == "junos" 

  - name: VyOS fact collection
    vyos_facts:
      gather_subset: all
    when: ansible_network_os == "vyos"              

  - name: Create dir to save switch config backups
    file:
      path: ~/ans/backup/{{ result.stdout }}/
      state: directory    # Playbook will FAIL without this directory

  - name: Save out backed up configuration       
    copy:
      content: "{{ ansible_net_config }}"
      dest: "~/ans/backup/{{ result.stdout }}/{{ inventory_hostname }}-config.backup"

  - name: Archival process
    archive:
      path: "~/ans/backup/{{ result.stdout }}/{{ inventory_hostname }}-config.backup"
      remove: True     # removes the original file
